"""Catalogo de textos da interface em varios idiomas (i18n).
GERADO AUTOMATICAMENTE por _build_lang.py - nao edite a mao;
edite _i18n/*.json e rode: python _build_lang.py"""
import os

SUPPORTED = ["en", "pt", "de", "es", "fr", "it", "ja", "ko", "pl", "ru", "tr", "zh"]

STRINGS = {
    "en": {
        "arg_desc": "Sync the lyrics of the song you're playing to your Discord status.",
        "arg_preview_win": "Show the lyrics in the terminal without touching Discord (no token needed).",
        "arg_preview": "Show the lyrics in the terminal without touching Discord.",
        "arg_interval": "Seconds between status updates (between {min} and {max}; default {default}). Higher = safer. When set, it is saved for next runs.",
        "sp_arg_interval": "Seconds between status updates ({min}-{max}; default from config or {default}). Higher = safer.",
        "arg_set_interval": "Only save the interval (in seconds) and exit, without starting.",
        "arg_lang": "Interface language code (e.g. en, pt, es). Default: auto-detect.",
        "arg_set_lang": "Save the interface language and exit (don't start).",
        "interval_saved_exit": "Interval set to {v}s (allowed: {min}-{max}s).",
        "interval_save_failed": "Couldn't save: {error}",
        "interval_out_of_range": "Interval out of range; adjusted to {v}s (min {min}s / max {max}s).",
        "interval_set_running": "Interval: {v}s (saved for next runs).",
        "token_none_yet": "No token saved yet.",
        "token_paste_prompt": "Paste your Discord token and press Enter (or leave empty to quit).",
        "token_local_note": "(The token stays only on this PC, in token.txt. NEVER share it.)",
        "token_saved_starting": "Token saved! Starting...",
        "token_save_failed": "Couldn't save the token: {error}",
        "token_not_found": "No token found.\nSet the DISCORD_TOKEN environment variable, or create a\ntoken.txt file (in the same folder) with your token in it.\n\nTip: run with --preview to test without a token.",
        "token_invalid_401": "[error] Invalid token (401). Check your DISCORD_TOKEN.",
        "preview_banner": "[ PREVIEW MODE - your Discord status will not be changed ]",
        "detecting_music": "Detecting music...",
        "lbl_song": "Song",
        "lbl_artist": "Artist",
        "lbl_time": "Time",
        "lbl_lyrics": "Lyrics",
        "lang_set": "Language set to: {lang}",
        "lang_invalid": "Unknown language '{lang}'. Available: {list}",
        "sp_arg_desc": "Discord Lyrics Status via the Spotify API.",
        "config_not_found": "config.json not found. Run this first:  python setup_spotify.py",
        "discord_401": "[error] Invalid Discord token (401).",
        "discord_token_missing_cfg": "discord_token is missing in config.json. Run setup_spotify.py again.",
        "detecting_spotify": "Detecting music on Spotify... (Ctrl+C to quit)",
        "exiting": "Exiting.",
        "setup_title": "Setup - Discord Lyrics Status (Spotify version)",
        "setup_step1": "STEP 1) Create an app at: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - Click 'Create app'.",
        "setup_step1_b": "   - Under 'Redirect URIs' add EXACTLY this address:",
        "setup_step1_c": "   - Save, then copy the 'Client ID' and the 'Client Secret'.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret are required.",
        "setup_step2": "STEP 2) Open this link in your browser, log in and click 'Agree':",
        "setup_step2_a": "   You will be redirected to something like:",
        "setup_step2_b": "   The page may say 'can't reach this page' - that's OK!",
        "setup_step2_c": "   What matters is the full URL left in the address bar.",
        "setup_step3": "STEP 3) Paste here the full URL you were redirected to: ",
        "code_not_found": "Couldn't find the 'code' in the URL.",
        "token_exchange_failed": "Failed to exchange the code for a token:",
        "no_refresh_token": "Spotify did not return a refresh_token:",
        "spotify_connected": "Spotify connected successfully!",
        "setup_step4": "STEP 4) Paste your Discord token.",
        "setup_step4_a": "   (How to get it: see the README. NEVER share this token.)",
        "prompt_discord_token": "Discord token: ",
        "discord_required": "The Discord token is required.",
        "setup_step5": "STEP 5) Update frequency (between {min} and {max} seconds).",
        "setup_step5_a": "   Higher = fewer requests and safer. Press Enter for the default ({default}s).",
        "prompt_interval": "Interval in seconds: ",
        "invalid_using_default": "Invalid value; using {default}s.",
        "interval_arrow": "   -> interval: {v}s",
        "saved_to": "All saved to: {path}",
        "secrets_warning": "This file holds your secrets - do NOT share it and do NOT push it to git.",
        "now_run": "Now just run:  python lyrics_spotify.py",
        "setup_lang_prompt": "Language (en, pt, es, ...) [Enter = auto-detect]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "pt": {
        "arg_desc": "Sincroniza a letra da musica que esta tocando com o seu status do Discord.",
        "arg_preview_win": "Mostra a letra no terminal sem mexer no Discord (nao precisa de token).",
        "arg_preview": "Mostra a letra no terminal sem mexer no Discord.",
        "arg_interval": "Segundos entre atualizacoes do status (entre {min} e {max}; padrao {default}). Maior = mais seguro. Quando informado, fica salvo para as proximas vezes.",
        "sp_arg_interval": "Segundos entre atualizacoes do status ({min}-{max}; padrao do config ou {default}). Maior = mais seguro.",
        "arg_set_interval": "Apenas salva o intervalo (em segundos) e sai, sem iniciar.",
        "arg_lang": "Codigo do idioma da interface (ex.: en, pt, es). Padrao: detectar automaticamente.",
        "arg_set_lang": "Salva o idioma da interface e sai (nao inicia).",
        "interval_saved_exit": "Intervalo definido para {v}s (permitido: {min}-{max}s).",
        "interval_save_failed": "Nao consegui salvar: {error}",
        "interval_out_of_range": "Intervalo fora da faixa; ajustei para {v}s (min {min}s / max {max}s).",
        "interval_set_running": "Intervalo: {v}s (salvo para as proximas vezes).",
        "token_none_yet": "Nenhum token salvo ainda.",
        "token_paste_prompt": "Cole seu token do Discord e tecle Enter (ou deixe vazio para sair).",
        "token_local_note": "(O token fica salvo so neste PC, em token.txt. NUNCA compartilhe.)",
        "token_saved_starting": "Token salvo! Iniciando...",
        "token_save_failed": "Nao consegui salvar o token: {error}",
        "token_not_found": "Nenhum token encontrado.\nDefina a variavel de ambiente DISCORD_TOKEN, ou crie um arquivo\ntoken.txt (na mesma pasta) com o seu token dentro.\n\nDica: rode com --preview para testar sem token.",
        "token_invalid_401": "[erro] Token invalido (401). Verifique seu DISCORD_TOKEN.",
        "preview_banner": "[ MODO PREVIEW - o seu status do Discord nao sera alterado ]",
        "detecting_music": "Detectando musica...",
        "lbl_song": "Musica",
        "lbl_artist": "Artista",
        "lbl_time": "Tempo",
        "lbl_lyrics": "Letra",
        "lang_set": "Idioma definido para: {lang}",
        "lang_invalid": "Idioma desconhecido '{lang}'. Disponiveis: {list}",
        "sp_arg_desc": "Discord Lyrics Status pela API do Spotify.",
        "config_not_found": "config.json nao encontrado. Rode primeiro:  python setup_spotify.py",
        "discord_401": "[erro] Token do Discord invalido (401).",
        "discord_token_missing_cfg": "discord_token ausente no config.json. Rode o setup_spotify.py de novo.",
        "detecting_spotify": "Detectando musica no Spotify... (Ctrl+C para sair)",
        "exiting": "Saindo.",
        "setup_title": "Configuracao - Discord Lyrics Status (versao Spotify)",
        "setup_step1": "PASSO 1) Crie um app em: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - Clique em 'Create app'.",
        "setup_step1_b": "   - Em 'Redirect URIs' adicione EXATAMENTE este endereco:",
        "setup_step1_c": "   - Salve e copie o 'Client ID' e o 'Client Secret'.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret sao obrigatorios.",
        "setup_step2": "PASSO 2) Abra este link no navegador, faca login e clique em 'Agree':",
        "setup_step2_a": "   Voce sera redirecionado para algo como:",
        "setup_step2_b": "   A pagina pode mostrar 'nao foi possivel acessar' - tudo bem!",
        "setup_step2_c": "   O que importa e a URL inteira que ficou na barra de endereco.",
        "setup_step3": "PASSO 3) Cole aqui a URL completa para onde voce foi redirecionado: ",
        "code_not_found": "Nao consegui encontrar o 'code' na URL.",
        "token_exchange_failed": "Falha ao trocar o code por token:",
        "no_refresh_token": "O Spotify nao retornou um refresh_token:",
        "spotify_connected": "Spotify conectado com sucesso!",
        "setup_step4": "PASSO 4) Cole o seu token do Discord.",
        "setup_step4_a": "   (Como pegar: veja o README. NUNCA compartilhe esse token.)",
        "prompt_discord_token": "Token do Discord: ",
        "discord_required": "O token do Discord e obrigatorio.",
        "setup_step5": "PASSO 5) Frequencia de atualizacao (entre {min} e {max} segundos).",
        "setup_step5_a": "   Maior = menos requisicoes e mais seguro. Tecle Enter para o padrao ({default}s).",
        "prompt_interval": "Intervalo em segundos: ",
        "invalid_using_default": "Valor invalido; usando {default}s.",
        "interval_arrow": "   -> intervalo: {v}s",
        "saved_to": "Tudo salvo em: {path}",
        "secrets_warning": "Este arquivo guarda seus segredos - NAO compartilhe e NAO suba pro git.",
        "now_run": "Agora e so rodar:  python lyrics_spotify.py",
        "setup_lang_prompt": "Idioma (en, pt, es, ...) [Enter = detectar automaticamente]: ",
        "tray_pause": "Pausar",
        "tray_resume": "Retomar",
        "tray_quit": "Sair",
        "tray_running": "Discord Lyrics: rodando",
        "tray_paused": "Discord Lyrics: pausado",
        "tray_no_token": "Nenhum token salvo - rode o configurar_token.bat antes",
    },
    "de": {
        "arg_desc": "Synchronisiert den Liedtext des laufenden Songs mit deinem Discord-Status.",
        "arg_preview_win": "Zeigt den Text im Terminal an, ohne Discord zu beruhren (kein Token notig).",
        "arg_preview": "Zeigt den Text im Terminal an, ohne Discord zu beruhren.",
        "arg_interval": "Sekunden zwischen Status-Updates (zwischen {min} und {max}; Standard {default}). Hoher = sicherer. Wenn angegeben, wird es fur die nachsten Male gespeichert.",
        "sp_arg_interval": "Sekunden zwischen Status-Updates ({min}-{max}; Standard aus der Config oder {default}). Hoher = sicherer.",
        "arg_set_interval": "Speichert nur das Intervall (in Sekunden) und beendet, ohne zu starten.",
        "arg_lang": "Sprachcode der Oberflache (z. B. en, pt, es). Standard: automatisch erkennen.",
        "arg_set_lang": "Speichert die Sprache der Oberflache und beendet (startet nicht).",
        "interval_saved_exit": "Intervall auf {v}s gesetzt (erlaubt: {min}-{max}s).",
        "interval_save_failed": "Speichern fehlgeschlagen: {error}",
        "interval_out_of_range": "Intervall ausserhalb des Bereichs; auf {v}s angepasst (min {min}s / max {max}s).",
        "interval_set_running": "Intervall: {v}s (fur die nachsten Male gespeichert).",
        "token_none_yet": "Noch kein Token gespeichert.",
        "token_paste_prompt": "Fuge deinen Discord-Token ein und druck Enter (oder leer lassen zum Beenden).",
        "token_local_note": "(Der Token bleibt nur auf diesem PC, in token.txt. Teile ihn NIEMALS.)",
        "token_saved_starting": "Token gespeichert! Starte...",
        "token_save_failed": "Token konnte nicht gespeichert werden: {error}",
        "token_not_found": "Kein Token gefunden.\nSetze die Umgebungsvariable DISCORD_TOKEN oder erstelle eine\ntoken.txt (im selben Ordner) mit deinem Token darin.\n\nTipp: Mit --preview starten, um ohne Token zu testen.",
        "token_invalid_401": "[Fehler] Ungultiger Token (401). Prufe deinen DISCORD_TOKEN.",
        "preview_banner": "[ PREVIEW-MODUS - dein Discord-Status wird nicht geandert ]",
        "detecting_music": "Suche nach Musik...",
        "lbl_song": "Titel",
        "lbl_artist": "Kunstler",
        "lbl_time": "Zeit",
        "lbl_lyrics": "Text",
        "lang_set": "Sprache gesetzt auf: {lang}",
        "lang_invalid": "Unbekannte Sprache '{lang}'. Verfugbar: {list}",
        "sp_arg_desc": "Discord Lyrics Status uber die Spotify-API.",
        "config_not_found": "config.json nicht gefunden. Fuhre zuerst aus:  python setup_spotify.py",
        "discord_401": "[Fehler] Ungultiger Discord-Token (401).",
        "discord_token_missing_cfg": "discord_token fehlt in config.json. Fuhre setup_spotify.py erneut aus.",
        "detecting_spotify": "Suche nach Musik bei Spotify... (Ctrl+C zum Beenden)",
        "exiting": "Beende.",
        "setup_title": "Einrichtung - Discord Lyrics Status (Spotify-Version)",
        "setup_step1": "SCHRITT 1) Erstelle eine App unter: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - Klicke auf 'Create app'.",
        "setup_step1_b": "   - Fuge unter 'Redirect URIs' GENAU diese Adresse hinzu:",
        "setup_step1_c": "   - Speichere und kopiere die 'Client ID' und das 'Client Secret'.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret sind erforderlich.",
        "setup_step2": "SCHRITT 2) Offne diesen Link im Browser, melde dich an und klicke auf 'Agree':",
        "setup_step2_a": "   Du wirst zu etwas wie diesem weitergeleitet:",
        "setup_step2_b": "   Die Seite zeigt evtl. 'Seite nicht erreichbar' - das ist okay!",
        "setup_step2_c": "   Wichtig ist die komplette URL in der Adressleiste.",
        "setup_step3": "SCHRITT 3) Fuge hier die komplette URL ein, zu der du weitergeleitet wurdest: ",
        "code_not_found": "Konnte den 'code' in der URL nicht finden.",
        "token_exchange_failed": "Austausch des code gegen ein Token fehlgeschlagen:",
        "no_refresh_token": "Spotify hat keinen refresh_token zuruckgegeben:",
        "spotify_connected": "Spotify erfolgreich verbunden!",
        "setup_step4": "SCHRITT 4) Fuge deinen Discord-Token ein.",
        "setup_step4_a": "   (Wie du ihn bekommst: siehe README. Teile diesen Token NIEMALS.)",
        "prompt_discord_token": "Discord-Token: ",
        "discord_required": "Der Discord-Token ist erforderlich.",
        "setup_step5": "SCHRITT 5) Aktualisierungsrate (zwischen {min} und {max} Sekunden).",
        "setup_step5_a": "   Hoher = weniger Anfragen und sicherer. Enter fur den Standard ({default}s).",
        "prompt_interval": "Intervall in Sekunden: ",
        "invalid_using_default": "Ungultiger Wert; verwende {default}s.",
        "interval_arrow": "   -> Intervall: {v}s",
        "saved_to": "Alles gespeichert in: {path}",
        "secrets_warning": "Diese Datei enthalt deine Geheimnisse - NICHT teilen und NICHT zu git pushen.",
        "now_run": "Jetzt einfach ausfuhren:  python lyrics_spotify.py",
        "setup_lang_prompt": "Sprache (en, pt, es, ...) [Enter = automatisch erkennen]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "es": {
        "arg_desc": "Sincroniza la letra de la cancion que estas escuchando con tu estado de Discord.",
        "arg_preview_win": "Muestra la letra en la terminal sin tocar Discord (no necesita token).",
        "arg_preview": "Muestra la letra en la terminal sin tocar Discord.",
        "arg_interval": "Segundos entre actualizaciones del estado (entre {min} y {max}; por defecto {default}). Mayor = mas seguro. Cuando se indica, se guarda para las proximas veces.",
        "sp_arg_interval": "Segundos entre actualizaciones del estado ({min}-{max}; por defecto el del config o {default}). Mayor = mas seguro.",
        "arg_set_interval": "Solo guarda el intervalo (en segundos) y sale, sin iniciar.",
        "arg_lang": "Codigo del idioma de la interfaz (p. ej. en, pt, es). Por defecto: deteccion automatica.",
        "arg_set_lang": "Guarda el idioma de la interfaz y sale (no inicia).",
        "interval_saved_exit": "Intervalo establecido en {v}s (permitido: {min}-{max}s).",
        "interval_save_failed": "No se pudo guardar: {error}",
        "interval_out_of_range": "Intervalo fuera de rango; ajustado a {v}s (min {min}s / max {max}s).",
        "interval_set_running": "Intervalo: {v}s (guardado para las proximas veces).",
        "token_none_yet": "Aun no hay ningun token guardado.",
        "token_paste_prompt": "Pega tu token de Discord y pulsa Enter (o dejalo vacio para salir).",
        "token_local_note": "(El token se guarda solo en este PC, en token.txt. NUNCA lo compartas.)",
        "token_saved_starting": "Token guardado! Iniciando...",
        "token_save_failed": "No se pudo guardar el token: {error}",
        "token_not_found": "No se encontro ningun token.\nDefine la variable de entorno DISCORD_TOKEN, o crea un archivo\ntoken.txt (en la misma carpeta) con tu token dentro.\n\nConsejo: ejecuta con --preview para probar sin token.",
        "token_invalid_401": "[error] Token invalido (401). Revisa tu DISCORD_TOKEN.",
        "preview_banner": "[ MODO PREVIEW - tu estado de Discord no se modificara ]",
        "detecting_music": "Detectando musica...",
        "lbl_song": "Cancion",
        "lbl_artist": "Artista",
        "lbl_time": "Tiempo",
        "lbl_lyrics": "Letra",
        "lang_set": "Idioma establecido en: {lang}",
        "lang_invalid": "Idioma desconocido '{lang}'. Disponibles: {list}",
        "sp_arg_desc": "Discord Lyrics Status mediante la API de Spotify.",
        "config_not_found": "config.json no encontrado. Ejecuta primero:  python setup_spotify.py",
        "discord_401": "[error] Token de Discord invalido (401).",
        "discord_token_missing_cfg": "Falta discord_token en config.json. Ejecuta setup_spotify.py de nuevo.",
        "detecting_spotify": "Detectando musica en Spotify... (Ctrl+C para salir)",
        "exiting": "Saliendo.",
        "setup_title": "Configuracion - Discord Lyrics Status (version Spotify)",
        "setup_step1": "PASO 1) Crea una app en: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - Haz clic en 'Create app'.",
        "setup_step1_b": "   - En 'Redirect URIs' anade EXACTAMENTE esta direccion:",
        "setup_step1_c": "   - Guarda y copia el 'Client ID' y el 'Client Secret'.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret son obligatorios.",
        "setup_step2": "PASO 2) Abre este enlace en el navegador, inicia sesion y haz clic en 'Agree':",
        "setup_step2_a": "   Seras redirigido a algo como:",
        "setup_step2_b": "   La pagina puede mostrar 'no se puede acceder' - no pasa nada!",
        "setup_step2_c": "   Lo que importa es la URL completa que quedo en la barra de direcciones.",
        "setup_step3": "PASO 3) Pega aqui la URL completa a la que fuiste redirigido: ",
        "code_not_found": "No se pudo encontrar el 'code' en la URL.",
        "token_exchange_failed": "Fallo al intercambiar el code por un token:",
        "no_refresh_token": "Spotify no devolvio un refresh_token:",
        "spotify_connected": "Spotify conectado con exito!",
        "setup_step4": "PASO 4) Pega tu token de Discord.",
        "setup_step4_a": "   (Como obtenerlo: mira el README. NUNCA compartas este token.)",
        "prompt_discord_token": "Token de Discord: ",
        "discord_required": "El token de Discord es obligatorio.",
        "setup_step5": "PASO 5) Frecuencia de actualizacion (entre {min} y {max} segundos).",
        "setup_step5_a": "   Mayor = menos solicitudes y mas seguro. Pulsa Enter para el valor por defecto ({default}s).",
        "prompt_interval": "Intervalo en segundos: ",
        "invalid_using_default": "Valor invalido; usando {default}s.",
        "interval_arrow": "   -> intervalo: {v}s",
        "saved_to": "Todo guardado en: {path}",
        "secrets_warning": "Este archivo guarda tus secretos - NO lo compartas y NO lo subas a git.",
        "now_run": "Ahora solo ejecuta:  python lyrics_spotify.py",
        "setup_lang_prompt": "Idioma (en, pt, es, ...) [Enter = deteccion automatica]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "fr": {
        "arg_desc": "Synchronise les paroles de la chanson en cours avec votre statut Discord.",
        "arg_preview_win": "Affiche les paroles dans le terminal sans toucher a Discord (aucun token requis).",
        "arg_preview": "Affiche les paroles dans le terminal sans toucher a Discord.",
        "arg_interval": "Secondes entre les mises a jour du statut (entre {min} et {max}; par defaut {default}). Plus grand = plus sur. Si indique, c'est enregistre pour les prochaines fois.",
        "sp_arg_interval": "Secondes entre les mises a jour du statut ({min}-{max}; par defaut celui du config ou {default}). Plus grand = plus sur.",
        "arg_set_interval": "Enregistre seulement l'intervalle (en secondes) et quitte, sans demarrer.",
        "arg_lang": "Code de langue de l'interface (ex. en, pt, es). Par defaut : detection automatique.",
        "arg_set_lang": "Enregistre la langue de l'interface et quitte (ne demarre pas).",
        "interval_saved_exit": "Intervalle defini a {v}s (autorise : {min}-{max}s).",
        "interval_save_failed": "Impossible d'enregistrer : {error}",
        "interval_out_of_range": "Intervalle hors plage ; ajuste a {v}s (min {min}s / max {max}s).",
        "interval_set_running": "Intervalle : {v}s (enregistre pour les prochaines fois).",
        "token_none_yet": "Aucun token enregistre pour l'instant.",
        "token_paste_prompt": "Collez votre token Discord et appuyez sur Entree (ou laissez vide pour quitter).",
        "token_local_note": "(Le token reste uniquement sur ce PC, dans token.txt. Ne le partagez JAMAIS.)",
        "token_saved_starting": "Token enregistre ! Demarrage...",
        "token_save_failed": "Impossible d'enregistrer le token : {error}",
        "token_not_found": "Aucun token trouve.\nDefinissez la variable d'environnement DISCORD_TOKEN, ou creez un fichier\ntoken.txt (dans le meme dossier) contenant votre token.\n\nAstuce : lancez avec --preview pour tester sans token.",
        "token_invalid_401": "[erreur] Token invalide (401). Verifiez votre DISCORD_TOKEN.",
        "preview_banner": "[ MODE PREVIEW - votre statut Discord ne sera pas modifie ]",
        "detecting_music": "Detection de la musique...",
        "lbl_song": "Titre",
        "lbl_artist": "Artiste",
        "lbl_time": "Temps",
        "lbl_lyrics": "Paroles",
        "lang_set": "Langue definie sur : {lang}",
        "lang_invalid": "Langue inconnue '{lang}'. Disponibles : {list}",
        "sp_arg_desc": "Discord Lyrics Status via l'API Spotify.",
        "config_not_found": "config.json introuvable. Lancez d'abord :  python setup_spotify.py",
        "discord_401": "[erreur] Token Discord invalide (401).",
        "discord_token_missing_cfg": "discord_token manquant dans config.json. Relancez setup_spotify.py.",
        "detecting_spotify": "Detection de la musique sur Spotify... (Ctrl+C pour quitter)",
        "exiting": "Fermeture.",
        "setup_title": "Configuration - Discord Lyrics Status (version Spotify)",
        "setup_step1": "ETAPE 1) Creez une app sur : https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - Cliquez sur 'Create app'.",
        "setup_step1_b": "   - Dans 'Redirect URIs' ajoutez EXACTEMENT cette adresse :",
        "setup_step1_c": "   - Enregistrez et copiez le 'Client ID' et le 'Client Secret'.",
        "prompt_client_id": "Client ID : ",
        "prompt_client_secret": "Client Secret : ",
        "client_required": "Client ID/Secret sont obligatoires.",
        "setup_step2": "ETAPE 2) Ouvrez ce lien dans le navigateur, connectez-vous et cliquez sur 'Agree' :",
        "setup_step2_a": "   Vous serez redirige vers quelque chose comme :",
        "setup_step2_b": "   La page peut afficher 'impossible d'acceder a cette page' - pas grave !",
        "setup_step2_c": "   Ce qui compte, c'est l'URL complete restee dans la barre d'adresse.",
        "setup_step3": "ETAPE 3) Collez ici l'URL complete vers laquelle vous avez ete redirige : ",
        "code_not_found": "Impossible de trouver le 'code' dans l'URL.",
        "token_exchange_failed": "Echec de l'echange du code contre un token :",
        "no_refresh_token": "Spotify n'a pas renvoye de refresh_token :",
        "spotify_connected": "Spotify connecte avec succes !",
        "setup_step4": "ETAPE 4) Collez votre token Discord.",
        "setup_step4_a": "   (Comment l'obtenir : voir le README. Ne partagez JAMAIS ce token.)",
        "prompt_discord_token": "Token Discord : ",
        "discord_required": "Le token Discord est obligatoire.",
        "setup_step5": "ETAPE 5) Frequence de mise a jour (entre {min} et {max} secondes).",
        "setup_step5_a": "   Plus grand = moins de requetes et plus sur. Entree pour la valeur par defaut ({default}s).",
        "prompt_interval": "Intervalle en secondes : ",
        "invalid_using_default": "Valeur invalide ; utilisation de {default}s.",
        "interval_arrow": "   -> intervalle : {v}s",
        "saved_to": "Tout enregistre dans : {path}",
        "secrets_warning": "Ce fichier contient vos secrets - ne le partagez PAS et ne le poussez PAS sur git.",
        "now_run": "Maintenant lancez simplement :  python lyrics_spotify.py",
        "setup_lang_prompt": "Langue (en, pt, es, ...) [Entree = detection automatique] : ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "it": {
        "arg_desc": "Sincronizza il testo della canzone in riproduzione con il tuo stato di Discord.",
        "arg_preview_win": "Mostra il testo nel terminale senza toccare Discord (nessun token necessario).",
        "arg_preview": "Mostra il testo nel terminale senza toccare Discord.",
        "arg_interval": "Secondi tra gli aggiornamenti dello stato (tra {min} e {max}; predefinito {default}). Piu alto = piu sicuro. Se indicato, viene salvato per le prossime volte.",
        "sp_arg_interval": "Secondi tra gli aggiornamenti dello stato ({min}-{max}; predefinito dal config o {default}). Piu alto = piu sicuro.",
        "arg_set_interval": "Salva solo l'intervallo (in secondi) ed esce, senza avviare.",
        "arg_lang": "Codice lingua dell'interfaccia (es. en, pt, es). Predefinito: rilevamento automatico.",
        "arg_set_lang": "Salva la lingua dell'interfaccia ed esce (non avvia).",
        "interval_saved_exit": "Intervallo impostato a {v}s (consentito: {min}-{max}s).",
        "interval_save_failed": "Impossibile salvare: {error}",
        "interval_out_of_range": "Intervallo fuori intervallo; regolato a {v}s (min {min}s / max {max}s).",
        "interval_set_running": "Intervallo: {v}s (salvato per le prossime volte).",
        "token_none_yet": "Nessun token salvato ancora.",
        "token_paste_prompt": "Incolla il tuo token di Discord e premi Invio (o lascia vuoto per uscire).",
        "token_local_note": "(Il token resta solo su questo PC, in token.txt. Non condividerlo MAI.)",
        "token_saved_starting": "Token salvato! Avvio...",
        "token_save_failed": "Impossibile salvare il token: {error}",
        "token_not_found": "Nessun token trovato.\nImposta la variabile d'ambiente DISCORD_TOKEN, oppure crea un file\ntoken.txt (nella stessa cartella) con il tuo token dentro.\n\nSuggerimento: avvia con --preview per provare senza token.",
        "token_invalid_401": "[errore] Token non valido (401). Controlla il tuo DISCORD_TOKEN.",
        "preview_banner": "[ MODALITA PREVIEW - il tuo stato di Discord non sara modificato ]",
        "detecting_music": "Rilevamento musica...",
        "lbl_song": "Brano",
        "lbl_artist": "Artista",
        "lbl_time": "Tempo",
        "lbl_lyrics": "Testo",
        "lang_set": "Lingua impostata su: {lang}",
        "lang_invalid": "Lingua sconosciuta '{lang}'. Disponibili: {list}",
        "sp_arg_desc": "Discord Lyrics Status tramite l'API di Spotify.",
        "config_not_found": "config.json non trovato. Esegui prima:  python setup_spotify.py",
        "discord_401": "[errore] Token di Discord non valido (401).",
        "discord_token_missing_cfg": "discord_token mancante in config.json. Esegui di nuovo setup_spotify.py.",
        "detecting_spotify": "Rilevamento musica su Spotify... (Ctrl+C per uscire)",
        "exiting": "Uscita.",
        "setup_title": "Configurazione - Discord Lyrics Status (versione Spotify)",
        "setup_step1": "PASSO 1) Crea un'app su: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - Clicca su 'Create app'.",
        "setup_step1_b": "   - In 'Redirect URIs' aggiungi ESATTAMENTE questo indirizzo:",
        "setup_step1_c": "   - Salva e copia il 'Client ID' e il 'Client Secret'.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret sono obbligatori.",
        "setup_step2": "PASSO 2) Apri questo link nel browser, accedi e clicca su 'Agree':",
        "setup_step2_a": "   Verrai reindirizzato a qualcosa come:",
        "setup_step2_b": "   La pagina potrebbe mostrare 'impossibile raggiungere' - va bene cosi!",
        "setup_step2_c": "   Cio che conta e l'URL completo rimasto nella barra degli indirizzi.",
        "setup_step3": "PASSO 3) Incolla qui l'URL completo a cui sei stato reindirizzato: ",
        "code_not_found": "Impossibile trovare il 'code' nell'URL.",
        "token_exchange_failed": "Scambio del code con un token non riuscito:",
        "no_refresh_token": "Spotify non ha restituito un refresh_token:",
        "spotify_connected": "Spotify connesso con successo!",
        "setup_step4": "PASSO 4) Incolla il tuo token di Discord.",
        "setup_step4_a": "   (Come ottenerlo: vedi il README. Non condividere MAI questo token.)",
        "prompt_discord_token": "Token di Discord: ",
        "discord_required": "Il token di Discord e obbligatorio.",
        "setup_step5": "PASSO 5) Frequenza di aggiornamento (tra {min} e {max} secondi).",
        "setup_step5_a": "   Piu alto = meno richieste e piu sicuro. Premi Invio per il predefinito ({default}s).",
        "prompt_interval": "Intervallo in secondi: ",
        "invalid_using_default": "Valore non valido; uso {default}s.",
        "interval_arrow": "   -> intervallo: {v}s",
        "saved_to": "Tutto salvato in: {path}",
        "secrets_warning": "Questo file contiene i tuoi segreti - NON condividerlo e NON caricarlo su git.",
        "now_run": "Ora basta eseguire:  python lyrics_spotify.py",
        "setup_lang_prompt": "Lingua (en, pt, es, ...) [Invio = rilevamento automatico]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "ja": {
        "arg_desc": "再生中の曲の歌詞を Discord のステータスに同期します。",
        "arg_preview_win": "Discord を変更せずにターミナルに歌詞を表示します（トークン不要）。",
        "arg_preview": "Discord を変更せずにターミナルに歌詞を表示します。",
        "arg_interval": "ステータス更新の間隔（秒）（{min}〜{max}、デフォルト {default}）。大きいほど安全。指定すると次回以降も保存されます。",
        "sp_arg_interval": "ステータス更新の間隔（秒）（{min}-{max}、デフォルトは config または {default}）。大きいほど安全。",
        "arg_set_interval": "間隔（秒）を保存して終了します（起動しません）。",
        "arg_lang": "インターフェースの言語コード（例: en, pt, es）。デフォルト: 自動検出。",
        "arg_set_lang": "インターフェースの言語を保存して終了します（起動しません）。",
        "interval_saved_exit": "間隔を {v}s に設定しました（許可範囲: {min}-{max}s）。",
        "interval_save_failed": "保存できませんでした: {error}",
        "interval_out_of_range": "間隔が範囲外です。{v}s に調整しました（最小 {min}s / 最大 {max}s）。",
        "interval_set_running": "間隔: {v}s（次回以降も保存しました）。",
        "token_none_yet": "トークンはまだ保存されていません。",
        "token_paste_prompt": "Discord のトークンを貼り付けて Enter を押してください（空のままで終了）。",
        "token_local_note": "（トークンはこの PC の token.txt にのみ保存されます。絶対に共有しないでください。）",
        "token_saved_starting": "トークンを保存しました！開始します...",
        "token_save_failed": "トークンを保存できませんでした: {error}",
        "token_not_found": "トークンが見つかりません。\n環境変数 DISCORD_TOKEN を設定するか、同じフォルダに\ntoken.txt を作成してトークンを記入してください。\n\nヒント: --preview を付けるとトークンなしで試せます。",
        "token_invalid_401": "[エラー] トークンが無効です (401)。DISCORD_TOKEN を確認してください。",
        "preview_banner": "[ プレビューモード - Discord のステータスは変更されません ]",
        "detecting_music": "音楽を検出中...",
        "lbl_song": "曲",
        "lbl_artist": "アーティスト",
        "lbl_time": "時間",
        "lbl_lyrics": "歌詞",
        "lang_set": "言語を次に設定しました: {lang}",
        "lang_invalid": "不明な言語 '{lang}'。利用可能: {list}",
        "sp_arg_desc": "Spotify API 経由の Discord Lyrics Status。",
        "config_not_found": "config.json が見つかりません。先に実行してください:  python setup_spotify.py",
        "discord_401": "[エラー] Discord のトークンが無効です (401)。",
        "discord_token_missing_cfg": "config.json に discord_token がありません。setup_spotify.py を再実行してください。",
        "detecting_spotify": "Spotify で音楽を検出中... (Ctrl+C で終了)",
        "exiting": "終了します。",
        "setup_title": "セットアップ - Discord Lyrics Status (Spotify 版)",
        "setup_step1": "ステップ 1) アプリを作成: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - 'Create app' をクリックします。",
        "setup_step1_b": "   - 'Redirect URIs' にこのアドレスを正確に追加します:",
        "setup_step1_c": "   - 保存して 'Client ID' と 'Client Secret' をコピーします。",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret は必須です。",
        "setup_step2": "ステップ 2) このリンクをブラウザで開き、ログインして 'Agree' をクリックします:",
        "setup_step2_a": "   次のような URL にリダイレクトされます:",
        "setup_step2_b": "   ページに「アクセスできません」と表示されても問題ありません！",
        "setup_step2_c": "   重要なのはアドレスバーに残った完全な URL です。",
        "setup_step3": "ステップ 3) リダイレクトされた完全な URL をここに貼り付けてください: ",
        "code_not_found": "URL から 'code' が見つかりませんでした。",
        "token_exchange_failed": "code とトークンの交換に失敗しました:",
        "no_refresh_token": "Spotify が refresh_token を返しませんでした:",
        "spotify_connected": "Spotify に正常に接続しました！",
        "setup_step4": "ステップ 4) Discord のトークンを貼り付けてください。",
        "setup_step4_a": "   （取得方法: README を参照。このトークンは絶対に共有しないでください。）",
        "prompt_discord_token": "Discord のトークン: ",
        "discord_required": "Discord のトークンは必須です。",
        "setup_step5": "ステップ 5) 更新頻度（{min}〜{max} 秒）。",
        "setup_step5_a": "   大きいほどリクエストが少なく安全です。Enter でデフォルト ({default}s)。",
        "prompt_interval": "間隔（秒）: ",
        "invalid_using_default": "無効な値です。{default}s を使用します。",
        "interval_arrow": "   -> 間隔: {v}s",
        "saved_to": "すべて保存しました: {path}",
        "secrets_warning": "このファイルには秘密情報が含まれます - 共有せず、git にアップロードしないでください。",
        "now_run": "あとは実行するだけ:  python lyrics_spotify.py",
        "setup_lang_prompt": "言語 (en, pt, es, ...) [Enter = 自動検出]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "ko": {
        "arg_desc": "재생 중인 곡의 가사를 Discord 상태 메시지에 동기화합니다.",
        "arg_preview_win": "Discord를 건드리지 않고 터미널에 가사를 표시합니다 (토큰 불필요).",
        "arg_preview": "Discord를 건드리지 않고 터미널에 가사를 표시합니다.",
        "arg_interval": "상태 업데이트 간격(초) ({min}~{max}, 기본값 {default}). 클수록 안전합니다. 지정하면 다음 실행에도 저장됩니다.",
        "sp_arg_interval": "상태 업데이트 간격(초) ({min}-{max}, 기본값은 config 또는 {default}). 클수록 안전합니다.",
        "arg_set_interval": "간격(초)만 저장하고 종료합니다 (실행하지 않음).",
        "arg_lang": "인터페이스 언어 코드 (예: en, pt, es). 기본값: 자동 감지.",
        "arg_set_lang": "인터페이스 언어를 저장하고 종료합니다 (실행하지 않음).",
        "interval_saved_exit": "간격을 {v}s로 설정했습니다 (허용: {min}-{max}s).",
        "interval_save_failed": "저장하지 못했습니다: {error}",
        "interval_out_of_range": "간격이 범위를 벗어났습니다. {v}s로 조정했습니다 (최소 {min}s / 최대 {max}s).",
        "interval_set_running": "간격: {v}s (다음 실행에도 저장됨).",
        "token_none_yet": "아직 저장된 토큰이 없습니다.",
        "token_paste_prompt": "Discord 토큰을 붙여넣고 Enter를 누르세요 (종료하려면 비워 두세요).",
        "token_local_note": "(토큰은 이 PC의 token.txt에만 저장됩니다. 절대 공유하지 마세요.)",
        "token_saved_starting": "토큰을 저장했습니다! 시작합니다...",
        "token_save_failed": "토큰을 저장하지 못했습니다: {error}",
        "token_not_found": "토큰을 찾을 수 없습니다.\n환경 변수 DISCORD_TOKEN을 설정하거나 같은 폴더에\ntoken.txt 파일을 만들어 토큰을 넣으세요.\n\n팁: --preview로 실행하면 토큰 없이 테스트할 수 있습니다.",
        "token_invalid_401": "[오류] 잘못된 토큰 (401). DISCORD_TOKEN을 확인하세요.",
        "preview_banner": "[ 미리보기 모드 - Discord 상태는 변경되지 않습니다 ]",
        "detecting_music": "음악 감지 중...",
        "lbl_song": "곡",
        "lbl_artist": "아티스트",
        "lbl_time": "시간",
        "lbl_lyrics": "가사",
        "lang_set": "언어를 다음으로 설정했습니다: {lang}",
        "lang_invalid": "알 수 없는 언어 '{lang}'. 사용 가능: {list}",
        "sp_arg_desc": "Spotify API를 통한 Discord Lyrics Status.",
        "config_not_found": "config.json을 찾을 수 없습니다. 먼저 실행하세요:  python setup_spotify.py",
        "discord_401": "[오류] 잘못된 Discord 토큰 (401).",
        "discord_token_missing_cfg": "config.json에 discord_token이 없습니다. setup_spotify.py를 다시 실행하세요.",
        "detecting_spotify": "Spotify에서 음악 감지 중... (Ctrl+C로 종료)",
        "exiting": "종료합니다.",
        "setup_title": "설정 - Discord Lyrics Status (Spotify 버전)",
        "setup_step1": "1단계) 앱을 만드세요: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - 'Create app'을 클릭합니다.",
        "setup_step1_b": "   - 'Redirect URIs'에 이 주소를 정확히 추가합니다:",
        "setup_step1_c": "   - 저장하고 'Client ID'와 'Client Secret'을 복사합니다.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret은 필수입니다.",
        "setup_step2": "2단계) 이 링크를 브라우저에서 열고 로그인한 뒤 'Agree'를 클릭합니다:",
        "setup_step2_a": "   다음과 같은 주소로 리디렉션됩니다:",
        "setup_step2_b": "   페이지에 '연결할 수 없음'이 표시되어도 괜찮습니다!",
        "setup_step2_c": "   중요한 것은 주소창에 남은 전체 URL입니다.",
        "setup_step3": "3단계) 리디렉션된 전체 URL을 여기에 붙여넣으세요: ",
        "code_not_found": "URL에서 'code'를 찾을 수 없습니다.",
        "token_exchange_failed": "code를 토큰으로 교환하지 못했습니다:",
        "no_refresh_token": "Spotify가 refresh_token을 반환하지 않았습니다:",
        "spotify_connected": "Spotify에 성공적으로 연결되었습니다!",
        "setup_step4": "4단계) Discord 토큰을 붙여넣으세요.",
        "setup_step4_a": "   (가져오는 방법: README 참조. 이 토큰은 절대 공유하지 마세요.)",
        "prompt_discord_token": "Discord 토큰: ",
        "discord_required": "Discord 토큰은 필수입니다.",
        "setup_step5": "5단계) 업데이트 빈도 ({min}~{max}초).",
        "setup_step5_a": "   클수록 요청이 적고 안전합니다. Enter는 기본값 ({default}s).",
        "prompt_interval": "간격(초): ",
        "invalid_using_default": "잘못된 값입니다. {default}s를 사용합니다.",
        "interval_arrow": "   -> 간격: {v}s",
        "saved_to": "모두 저장됨: {path}",
        "secrets_warning": "이 파일에는 비밀 정보가 들어 있습니다 - 공유하거나 git에 올리지 마세요.",
        "now_run": "이제 실행만 하면 됩니다:  python lyrics_spotify.py",
        "setup_lang_prompt": "언어 (en, pt, es, ...) [Enter = 자동 감지]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "pl": {
        "arg_desc": "Synchronizuje tekst odtwarzanej piosenki ze statusem na Discordzie.",
        "arg_preview_win": "Pokazuje tekst w terminalu bez ruszania Discorda (token niepotrzebny).",
        "arg_preview": "Pokazuje tekst w terminalu bez ruszania Discorda.",
        "arg_interval": "Sekundy między aktualizacjami statusu (od {min} do {max}; domyślnie {default}). Większe = bezpieczniejsze. Po podaniu zapisuje się na kolejne uruchomienia.",
        "sp_arg_interval": "Sekundy między aktualizacjami statusu ({min}-{max}; domyślnie z config lub {default}). Większe = bezpieczniejsze.",
        "arg_set_interval": "Tylko zapisuje interwał (w sekundach) i kończy, bez uruchamiania.",
        "arg_lang": "Kod języka interfejsu (np. en, pt, es). Domyślnie: automatyczne wykrywanie.",
        "arg_set_lang": "Zapisuje język interfejsu i kończy (nie uruchamia).",
        "interval_saved_exit": "Interwał ustawiony na {v}s (dozwolone: {min}-{max}s).",
        "interval_save_failed": "Nie udało się zapisać: {error}",
        "interval_out_of_range": "Interwał poza zakresem; dostosowano do {v}s (min {min}s / maks {max}s).",
        "interval_set_running": "Interwał: {v}s (zapisany na kolejne razy).",
        "token_none_yet": "Nie zapisano jeszcze żadnego tokenu.",
        "token_paste_prompt": "Wklej swój token Discorda i naciśnij Enter (lub zostaw puste, aby wyjść).",
        "token_local_note": "(Token jest przechowywany tylko na tym komputerze, w token.txt. NIGDY go nie udostępniaj.)",
        "token_saved_starting": "Token zapisany! Uruchamianie...",
        "token_save_failed": "Nie udało się zapisać tokenu: {error}",
        "token_not_found": "Nie znaleziono tokenu.\nUstaw zmienną środowiskową DISCORD_TOKEN lub utwórz plik\ntoken.txt (w tym samym folderze) ze swoim tokenem w środku.\n\nWskazówka: uruchom z --preview, aby przetestować bez tokenu.",
        "token_invalid_401": "[błąd] Nieprawidłowy token (401). Sprawdź swój DISCORD_TOKEN.",
        "preview_banner": "[ TRYB PODGLĄDU - Twój status na Discordzie nie zostanie zmieniony ]",
        "detecting_music": "Wykrywanie muzyki...",
        "lbl_song": "Utwór",
        "lbl_artist": "Wykonawca",
        "lbl_time": "Czas",
        "lbl_lyrics": "Tekst",
        "lang_set": "Język ustawiony na: {lang}",
        "lang_invalid": "Nieznany język '{lang}'. Dostępne: {list}",
        "sp_arg_desc": "Discord Lyrics Status przez API Spotify.",
        "config_not_found": "Nie znaleziono config.json. Najpierw uruchom:  python setup_spotify.py",
        "discord_401": "[błąd] Nieprawidłowy token Discorda (401).",
        "discord_token_missing_cfg": "Brak discord_token w config.json. Uruchom ponownie setup_spotify.py.",
        "detecting_spotify": "Wykrywanie muzyki w Spotify... (Ctrl+C, aby wyjść)",
        "exiting": "Zamykanie.",
        "setup_title": "Konfiguracja - Discord Lyrics Status (wersja Spotify)",
        "setup_step1": "KROK 1) Utwórz aplikację na: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - Kliknij 'Create app'.",
        "setup_step1_b": "   - W 'Redirect URIs' dodaj DOKŁADNIE ten adres:",
        "setup_step1_c": "   - Zapisz i skopiuj 'Client ID' oraz 'Client Secret'.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret są wymagane.",
        "setup_step2": "KROK 2) Otwórz ten link w przeglądarce, zaloguj się i kliknij 'Agree':",
        "setup_step2_a": "   Zostaniesz przekierowany do czegoś takiego:",
        "setup_step2_b": "   Strona może pokazać 'nie można uzyskać dostępu' - to w porządku!",
        "setup_step2_c": "   Liczy się pełny URL, który został w pasku adresu.",
        "setup_step3": "KROK 3) Wklej tutaj pełny URL, do którego zostałeś przekierowany: ",
        "code_not_found": "Nie udało się znaleźć 'code' w URL.",
        "token_exchange_failed": "Nie udało się wymienić code na token:",
        "no_refresh_token": "Spotify nie zwróciło refresh_token:",
        "spotify_connected": "Spotify połączone pomyślnie!",
        "setup_step4": "KROK 4) Wklej swój token Discorda.",
        "setup_step4_a": "   (Jak go zdobyć: zobacz README. NIGDY nie udostępniaj tego tokenu.)",
        "prompt_discord_token": "Token Discorda: ",
        "discord_required": "Token Discorda jest wymagany.",
        "setup_step5": "KROK 5) Częstotliwość aktualizacji (od {min} do {max} sekund).",
        "setup_step5_a": "   Większe = mniej żądań i bezpieczniej. Enter dla wartości domyślnej ({default}s).",
        "prompt_interval": "Interwał w sekundach: ",
        "invalid_using_default": "Nieprawidłowa wartość; używam {default}s.",
        "interval_arrow": "   -> interwał: {v}s",
        "saved_to": "Wszystko zapisano w: {path}",
        "secrets_warning": "Ten plik zawiera Twoje sekrety - NIE udostępniaj go i NIE wysyłaj na git.",
        "now_run": "Teraz po prostu uruchom:  python lyrics_spotify.py",
        "setup_lang_prompt": "Język (en, pt, es, ...) [Enter = automatyczne wykrywanie]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "ru": {
        "arg_desc": "Синхронизирует текст играющей песни с вашим статусом в Discord.",
        "arg_preview_win": "Показывает текст в терминале, не трогая Discord (токен не нужен).",
        "arg_preview": "Показывает текст в терминале, не трогая Discord.",
        "arg_interval": "Секунды между обновлениями статуса (от {min} до {max}; по умолчанию {default}). Больше = безопаснее. Если указано, сохраняется на следующие запуски.",
        "sp_arg_interval": "Секунды между обновлениями статуса ({min}-{max}; по умолчанию из config или {default}). Больше = безопаснее.",
        "arg_set_interval": "Только сохранить интервал (в секундах) и выйти, не запуская.",
        "arg_lang": "Код языка интерфейса (например, en, pt, es). По умолчанию: автоопределение.",
        "arg_set_lang": "Сохранить язык интерфейса и выйти (не запускать).",
        "interval_saved_exit": "Интервал установлен на {v}s (допустимо: {min}-{max}s).",
        "interval_save_failed": "Не удалось сохранить: {error}",
        "interval_out_of_range": "Интервал вне диапазона; скорректирован до {v}s (мин {min}s / макс {max}s).",
        "interval_set_running": "Интервал: {v}s (сохранён на следующие запуски).",
        "token_none_yet": "Токен ещё не сохранён.",
        "token_paste_prompt": "Вставьте свой токен Discord и нажмите Enter (или оставьте пустым для выхода).",
        "token_local_note": "(Токен хранится только на этом ПК, в token.txt. НИКОГДА не делитесь им.)",
        "token_saved_starting": "Токен сохранён! Запуск...",
        "token_save_failed": "Не удалось сохранить токен: {error}",
        "token_not_found": "Токен не найден.\nЗадайте переменную окружения DISCORD_TOKEN или создайте файл\ntoken.txt (в той же папке) со своим токеном внутри.\n\nСовет: запустите с --preview, чтобы проверить без токена.",
        "token_invalid_401": "[ошибка] Неверный токен (401). Проверьте свой DISCORD_TOKEN.",
        "preview_banner": "[ РЕЖИМ PREVIEW - ваш статус Discord не будет изменён ]",
        "detecting_music": "Определение музыки...",
        "lbl_song": "Песня",
        "lbl_artist": "Исполнитель",
        "lbl_time": "Время",
        "lbl_lyrics": "Текст",
        "lang_set": "Язык установлен на: {lang}",
        "lang_invalid": "Неизвестный язык '{lang}'. Доступны: {list}",
        "sp_arg_desc": "Discord Lyrics Status через API Spotify.",
        "config_not_found": "config.json не найден. Сначала запустите:  python setup_spotify.py",
        "discord_401": "[ошибка] Неверный токен Discord (401).",
        "discord_token_missing_cfg": "discord_token отсутствует в config.json. Запустите setup_spotify.py снова.",
        "detecting_spotify": "Определение музыки в Spotify... (Ctrl+C для выхода)",
        "exiting": "Выход.",
        "setup_title": "Настройка - Discord Lyrics Status (версия Spotify)",
        "setup_step1": "ШАГ 1) Создайте приложение на: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - Нажмите 'Create app'.",
        "setup_step1_b": "   - В 'Redirect URIs' добавьте ТОЧНО этот адрес:",
        "setup_step1_c": "   - Сохраните и скопируйте 'Client ID' и 'Client Secret'.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret обязательны.",
        "setup_step2": "ШАГ 2) Откройте эту ссылку в браузере, войдите и нажмите 'Agree':",
        "setup_step2_a": "   Вас перенаправит на что-то вроде:",
        "setup_step2_b": "   Страница может показать 'не удаётся открыть' - это нормально!",
        "setup_step2_c": "   Важен полный URL, оставшийся в адресной строке.",
        "setup_step3": "ШАГ 3) Вставьте сюда полный URL, на который вас перенаправило: ",
        "code_not_found": "Не удалось найти 'code' в URL.",
        "token_exchange_failed": "Не удалось обменять code на токен:",
        "no_refresh_token": "Spotify не вернул refresh_token:",
        "spotify_connected": "Spotify успешно подключён!",
        "setup_step4": "ШАГ 4) Вставьте свой токен Discord.",
        "setup_step4_a": "   (Как получить: смотрите README. НИКОГДА не делитесь этим токеном.)",
        "prompt_discord_token": "Токен Discord: ",
        "discord_required": "Токен Discord обязателен.",
        "setup_step5": "ШАГ 5) Частота обновления (от {min} до {max} секунд).",
        "setup_step5_a": "   Больше = меньше запросов и безопаснее. Enter - значение по умолчанию ({default}s).",
        "prompt_interval": "Интервал в секундах: ",
        "invalid_using_default": "Неверное значение; используется {default}s.",
        "interval_arrow": "   -> интервал: {v}s",
        "saved_to": "Всё сохранено в: {path}",
        "secrets_warning": "Этот файл хранит ваши секреты - НЕ делитесь им и НЕ загружайте в git.",
        "now_run": "Теперь просто запустите:  python lyrics_spotify.py",
        "setup_lang_prompt": "Язык (en, pt, es, ...) [Enter = автоопределение]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "tr": {
        "arg_desc": "Çalan şarkının sözlerini Discord durumunla senkronize eder.",
        "arg_preview_win": "Discord'a dokunmadan sözleri terminalde gösterir (token gerekmez).",
        "arg_preview": "Discord'a dokunmadan sözleri terminalde gösterir.",
        "arg_interval": "Durum güncellemeleri arası saniye ({min} ile {max} arası; varsayılan {default}). Büyük = daha güvenli. Belirtilirse sonraki çalıştırmalar için kaydedilir.",
        "sp_arg_interval": "Durum güncellemeleri arası saniye ({min}-{max}; varsayılan config'ten veya {default}). Büyük = daha güvenli.",
        "arg_set_interval": "Sadece aralığı (saniye) kaydeder ve çıkar, başlatmaz.",
        "arg_lang": "Arayüz dil kodu (örn. en, pt, es). Varsayılan: otomatik algıla.",
        "arg_set_lang": "Arayüz dilini kaydeder ve çıkar (başlatmaz).",
        "interval_saved_exit": "Aralık {v}s olarak ayarlandı (izin verilen: {min}-{max}s).",
        "interval_save_failed": "Kaydedilemedi: {error}",
        "interval_out_of_range": "Aralık sınır dışı; {v}s olarak ayarlandı (min {min}s / maks {max}s).",
        "interval_set_running": "Aralık: {v}s (sonraki çalıştırmalar için kaydedildi).",
        "token_none_yet": "Henüz kayıtlı token yok.",
        "token_paste_prompt": "Discord token'ını yapıştır ve Enter'a bas (çıkmak için boş bırak).",
        "token_local_note": "(Token yalnızca bu bilgisayarda, token.txt içinde tutulur. ASLA paylaşma.)",
        "token_saved_starting": "Token kaydedildi! Başlatılıyor...",
        "token_save_failed": "Token kaydedilemedi: {error}",
        "token_not_found": "Token bulunamadı.\nDISCORD_TOKEN ortam değişkenini ayarla ya da aynı klasörde\ntoken.txt dosyası oluşturup token'ını içine yaz.\n\nİpucu: token olmadan denemek için --preview ile çalıştır.",
        "token_invalid_401": "[hata] Geçersiz token (401). DISCORD_TOKEN'ını kontrol et.",
        "preview_banner": "[ ÖNİZLEME MODU - Discord durumun değiştirilmeyecek ]",
        "detecting_music": "Müzik algılanıyor...",
        "lbl_song": "Şarkı",
        "lbl_artist": "Sanatçı",
        "lbl_time": "Süre",
        "lbl_lyrics": "Sözler",
        "lang_set": "Dil şuna ayarlandı: {lang}",
        "lang_invalid": "Bilinmeyen dil '{lang}'. Mevcut: {list}",
        "sp_arg_desc": "Spotify API ile Discord Lyrics Status.",
        "config_not_found": "config.json bulunamadı. Önce çalıştır:  python setup_spotify.py",
        "discord_401": "[hata] Geçersiz Discord token'ı (401).",
        "discord_token_missing_cfg": "config.json içinde discord_token eksik. setup_spotify.py'yi tekrar çalıştır.",
        "detecting_spotify": "Spotify'da müzik algılanıyor... (Çıkmak için Ctrl+C)",
        "exiting": "Çıkılıyor.",
        "setup_title": "Kurulum - Discord Lyrics Status (Spotify sürümü)",
        "setup_step1": "ADIM 1) Şurada bir uygulama oluştur: https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - 'Create app'e tıkla.",
        "setup_step1_b": "   - 'Redirect URIs' kısmına TAM olarak bu adresi ekle:",
        "setup_step1_c": "   - Kaydet ve 'Client ID' ile 'Client Secret'i kopyala.",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret zorunludur.",
        "setup_step2": "ADIM 2) Bu bağlantıyı tarayıcıda aç, giriş yap ve 'Agree'ye tıkla:",
        "setup_step2_a": "   Şuna benzer bir adrese yönlendirileceksin:",
        "setup_step2_b": "   Sayfa 'bu sayfaya ulaşılamıyor' diyebilir - sorun değil!",
        "setup_step2_c": "   Önemli olan adres çubuğunda kalan tam URL'dir.",
        "setup_step3": "ADIM 3) Yönlendirildiğin tam URL'yi buraya yapıştır: ",
        "code_not_found": "URL'de 'code' bulunamadı.",
        "token_exchange_failed": "code'u token ile değiştirme başarısız:",
        "no_refresh_token": "Spotify bir refresh_token döndürmedi:",
        "spotify_connected": "Spotify başarıyla bağlandı!",
        "setup_step4": "ADIM 4) Discord token'ını yapıştır.",
        "setup_step4_a": "   (Nasıl alınır: README'ye bak. Bu token'ı ASLA paylaşma.)",
        "prompt_discord_token": "Discord token'ı: ",
        "discord_required": "Discord token'ı zorunludur.",
        "setup_step5": "ADIM 5) Güncelleme sıklığı ({min} ile {max} saniye arası).",
        "setup_step5_a": "   Büyük = daha az istek ve daha güvenli. Varsayılan için Enter ({default}s).",
        "prompt_interval": "Saniye cinsinden aralık: ",
        "invalid_using_default": "Geçersiz değer; {default}s kullanılıyor.",
        "interval_arrow": "   -> aralık: {v}s",
        "saved_to": "Her şey şuraya kaydedildi: {path}",
        "secrets_warning": "Bu dosya gizli bilgilerini içerir - paylaşma ve git'e yükleme.",
        "now_run": "Artık sadece çalıştır:  python lyrics_spotify.py",
        "setup_lang_prompt": "Dil (en, pt, es, ...) [Enter = otomatik algıla]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
    "zh": {
        "arg_desc": "将正在播放的歌曲歌词同步到你的 Discord 状态。",
        "arg_preview_win": "在终端显示歌词，不改动 Discord（无需令牌）。",
        "arg_preview": "在终端显示歌词，不改动 Discord。",
        "arg_interval": "状态更新之间的秒数（{min} 到 {max}，默认 {default}）。越大越安全。指定后会为下次保存。",
        "sp_arg_interval": "状态更新之间的秒数（{min}-{max}，默认取自 config 或 {default}）。越大越安全。",
        "arg_set_interval": "仅保存间隔（秒）并退出，不启动。",
        "arg_lang": "界面语言代码（例如 en、pt、es）。默认：自动检测。",
        "arg_set_lang": "保存界面语言并退出（不启动）。",
        "interval_saved_exit": "间隔已设为 {v}s（允许：{min}-{max}s）。",
        "interval_save_failed": "无法保存：{error}",
        "interval_out_of_range": "间隔超出范围；已调整为 {v}s（最小 {min}s / 最大 {max}s）。",
        "interval_set_running": "间隔：{v}s（已为下次保存）。",
        "token_none_yet": "尚未保存任何令牌。",
        "token_paste_prompt": "粘贴你的 Discord 令牌并按回车（留空则退出）。",
        "token_local_note": "（令牌只保存在本机的 token.txt 中。切勿分享。）",
        "token_saved_starting": "令牌已保存！正在启动...",
        "token_save_failed": "无法保存令牌：{error}",
        "token_not_found": "未找到令牌。\n请设置环境变量 DISCORD_TOKEN，或在同一文件夹创建\ntoken.txt 文件并把你的令牌写进去。\n\n提示：用 --preview 运行可在没有令牌时测试。",
        "token_invalid_401": "[错误] 令牌无效 (401)。请检查你的 DISCORD_TOKEN。",
        "preview_banner": "[ 预览模式 - 不会更改你的 Discord 状态 ]",
        "detecting_music": "正在检测音乐...",
        "lbl_song": "歌曲",
        "lbl_artist": "艺术家",
        "lbl_time": "时间",
        "lbl_lyrics": "歌词",
        "lang_set": "语言已设为：{lang}",
        "lang_invalid": "未知语言 '{lang}'。可用：{list}",
        "sp_arg_desc": "通过 Spotify API 的 Discord Lyrics Status。",
        "config_not_found": "未找到 config.json。请先运行：  python setup_spotify.py",
        "discord_401": "[错误] Discord 令牌无效 (401)。",
        "discord_token_missing_cfg": "config.json 中缺少 discord_token。请重新运行 setup_spotify.py。",
        "detecting_spotify": "正在 Spotify 检测音乐...（Ctrl+C 退出）",
        "exiting": "正在退出。",
        "setup_title": "设置 - Discord Lyrics Status（Spotify 版）",
        "setup_step1": "第 1 步) 在此创建应用：https://developer.spotify.com/dashboard",
        "setup_step1_a": "   - 点击 'Create app'。",
        "setup_step1_b": "   - 在 'Redirect URIs' 中准确添加此地址：",
        "setup_step1_c": "   - 保存并复制 'Client ID' 和 'Client Secret'。",
        "prompt_client_id": "Client ID: ",
        "prompt_client_secret": "Client Secret: ",
        "client_required": "Client ID/Secret 为必填项。",
        "setup_step2": "第 2 步) 在浏览器中打开此链接，登录并点击 'Agree'：",
        "setup_step2_a": "   你会被重定向到类似这样的地址：",
        "setup_step2_b": "   页面可能显示「无法访问」——没关系！",
        "setup_step2_c": "   重要的是地址栏中保留的完整 URL。",
        "setup_step3": "第 3 步) 把你被重定向到的完整 URL 粘贴到这里： ",
        "code_not_found": "无法在 URL 中找到 'code'。",
        "token_exchange_failed": "用 code 交换令牌失败：",
        "no_refresh_token": "Spotify 未返回 refresh_token：",
        "spotify_connected": "Spotify 连接成功！",
        "setup_step4": "第 4 步) 粘贴你的 Discord 令牌。",
        "setup_step4_a": "   （如何获取：见 README。切勿分享此令牌。）",
        "prompt_discord_token": "Discord 令牌: ",
        "discord_required": "Discord 令牌为必填项。",
        "setup_step5": "第 5 步) 更新频率（{min} 到 {max} 秒）。",
        "setup_step5_a": "   越大请求越少越安全。回车使用默认值（{default}s）。",
        "prompt_interval": "间隔（秒）: ",
        "invalid_using_default": "值无效；使用 {default}s。",
        "interval_arrow": "   -> 间隔：{v}s",
        "saved_to": "全部保存到：{path}",
        "secrets_warning": "此文件保存你的机密信息——请勿分享，也不要上传到 git。",
        "now_run": "现在只需运行：  python lyrics_spotify.py",
        "setup_lang_prompt": "语言 (en, pt, es, ...) [回车 = 自动检测]: ",
        "tray_pause": "Pause",
        "tray_resume": "Resume",
        "tray_quit": "Quit",
        "tray_running": "Discord Lyrics: running",
        "tray_paused": "Discord Lyrics: paused",
        "tray_no_token": "No token saved - run configurar_token.bat first",
    },
}


_LANG = "en"


def detect_lang():
    """Descobre o idioma do sistema (Windows/Unix). Cai para 'en' se nao houver."""
    code = ""
    try:
        if os.name == "nt":
            import ctypes
            import locale
            lcid = ctypes.windll.kernel32.GetUserDefaultUILanguage()
            code = locale.windows_locale.get(lcid, "")
    except Exception:
        code = ""
    if not code:
        for var in ("LANGUAGE", "LC_ALL", "LC_MESSAGES", "LANG"):
            code = os.environ.get(var, "")
            if code:
                break
    code = (code or "en").lower().replace("-", "_")
    base = code.split("_")[0].split(".")[0].split(":")[0]
    return base if base in STRINGS else "en"


def set_lang(lang):
    """Define o idioma se suportado; retorna o idioma em uso."""
    global _LANG
    if lang:
        base = str(lang).lower().replace("-", "_").split("_")[0]
        if base in STRINGS:
            _LANG = base
    return _LANG


def get_lang():
    return _LANG


def available():
    return list(STRINGS.keys())


def t(key, **kw):
    """Texto traduzido para a chave; cai para ingles, depois para a propria chave."""
    text = STRINGS.get(_LANG, {}).get(key) or STRINGS["en"].get(key) or key
    if kw:
        try:
            return text.format(**kw)
        except Exception:
            return text
    return text


_LANG = detect_lang()
